### ISSUE TITLE
Memory game doesn't work at all with Internet Explorer 11

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-memory-game#22]
Hello,

Memory game doesn't work at all with Internet Explorer 11, this have been broken at least since 1.0-rc8 and it's still in version 1.0. You can just open all the cards at once so the two card flipping functionaly doesn't work.

Tested with Moodle 3.1.3 and mod_hvp versions 1.0-rc.8 2017021500 and 1.0
2017031300, memory game module **Memory Game (1.2.1)**

**Comment by icc** [comment]
Hi, 
The faulty component has been fixed in otacke/h5p-timer@ef0afa6d957fa97a44ba798808385dae93241501.
If you want the fix for your site you can download the [Memory Game](h5p.org/memory-game) example and upload it either as a new activity or to the H5P Libraries section. This fix will be part of the next release. 
I'm sorry for the inconvenience.

**Comment by Jarvil** [comment]
Hello,

We already have mod_hvp 1.0 (2017031300);

https://moodle.org/plugins/pluginversions.php?plugin=mod_hvp

and  Memory Game (1.2.1) library so we have the newest version already?

**Comment by Jarvil** [comment]
Hello,

I updated the library and the memory game library version is still 1.2.1 but the problem was fixed, how is that the version number didn't change to 1.2.2 ?

**Comment by icc** [comment]
The issue was in a sub-component, H5P.Timer, and since it was a bug fix(patch version) it was the only library updated.
